### ISSUE TITLE
any simple pipeline description ?

### ISSUE THREAD

**Issue by hmyh1202** [scottgigante/haplotyped-methylome#1]
The pipeline of svg picture is so complex.

Do you have any simple shell code description?

**Comment by hmyh1202** [comment]
![default](https://user-images.githubusercontent.com/18067365/53707461-0bfb8800-3e6a-11e9-855b-cada0f260a1b.png)

**Comment by scottgigante** [comment]
Hi @hmyh1202 , sadly the svg picture is complex because the pipeline is complex :) The best I can do is point you to the smaller svgs at the bottom of the README, or otherwise you can read the rule descriptions in `scripts/*.snakefile`. These rules are executed in the order shown in the svg in order to produce the final output.

Regarding your question about DSS, we ran it twice, once for parent-of-origin effects, and once for strain-specific effects. Hence, to see parent-of-origin effects, we ran DSS treating the samples with the same parent as replicates; to see strain effects, we ran DSS treating the samples with the same strain as replicates. I hope that makes sense.

**Comment by hmyh1202** [comment]
Thans for your kind reply. 

Here, I have sequenced one father, one mother sample by using WGS, so got SNP data based on reference sequence. And I got four F1 samples data of RNA-seq and bisulfite-seq.  
The current situation I did not sequenced the reciprocal cross samples.

**Comment by scottgigante** [comment]
Hi @hmyh1202 , your design is fine to detect DMRs between maternal genome A and paternal genome B - DSS works with replicates of the same samples, and with four replicates you will get good results for detecting these DMRs. The challenge is that it is impossible to tell which of these DMRs are due to genome A vs genome B, and which of these are due to maternal vs paternal. 

To further deconvolve this you can run the reciprocal cross, either (as we did) treating the forward and reciprocal crosses as replicates (what we did) or by running the DMR selection separately and seeing which DMRs change direction (more appropriate if you have four replicates of each, in my opinion.)

I hope that makes sense!

**Comment by scottgigante** [comment]
Here is a paper describing the general experimental framework of DSS, if that is helpful: http://doi.org/10.1093/bioinformatics/btw026

**Comment by hmyh1202** [comment]
Thank you very much !
